      COMMON/BLK2/NA,NB,NP,NP2,NPEAK,ISTEP,IORIGN,
     1IROT,IIROT,JROT(3),IROTA,NSURF,IPOT,NPOTA,NPOTB,IOMTA,
     2IOMTB,KCUT,NCRES(20),IINTA,IINTB,NINTA(50),NINTB(50),
     3ISTAT,ISYMM,ISITA(5),ISITB(5),NSITA,NSITB,
     4IRESITA(5,50),IRESITB(5,50),IATSITA(1000,2),IATSITB(1000,2),
     5NATSITA,NATSITB,NTRIM,IHDRF,IREFN
C
      COMMON/BLK3/ORIG(3),STEPSZ,RAD,PI,TPEAK,RHO,RPOTA,RPOTB,
     1PP1,WF,CRES(20),XCUT,XRESL,DSYMM,ASYMM,XSITA(5),HD,DT,
     2XSITB(5),XXM

C
      COMMON/BLK5/OMITRHO
